version: '3.0'
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_training_basic
    volumes:
      - './:/go/src/my_application_name:rw'
    tty: true